### ISSUE TITLE
WB won't match file

### ISSUE THREAD

**Issue by j-ktz** [CodyBerenson/PGMA-Modernized#11] opened 2020-04-12 23:55 UTC
Not sure why this one won't match? I've tried with a curly apostrophe and a straight one...
https://www.waybig.com/blog/2006/01/18/cades-workout-corbinfisher/
<img width="557" alt="screenshot 2020-04-12 at 7 54 21 PM" src="https://user-images.githubusercontent.com/59346628/79082816-96fab300-7cf7-11ea-84ea-bd623e9bcf9b.png">

**Comment by CodyBerenson** [comment] 2020-04-13 00:12
@j-ktz 
I get the same results.  There is a blog entry for this scene on QC as well, but it doesn't match for me either....and no cover art.  

@jph71
Hey Jason, do you have any thoughts?

**Comment by j-ktz** [comment] 2020-04-13 00:37
Found another one that won't match but this is GayDVDEmpire, not WB. Tried using both the production year and release year. Can't get it to match.

https://www.gaydvdempire.com/2698404/jessie-colter-brock-avery-vs-seth-billy-santoro-live-fight-porn-videos.html

<img width="551" alt="screenshot 2020-04-12 at 8 36 46 PM" src="https://user-images.githubusercontent.com/59346628/79083612-5ef66e80-7cfd-11ea-9936-8ce4f5955876.png">

**Comment by JPH71** [comment] 2020-04-13 00:41
I will check it out...

**Comment by JPH71** [comment] 2020-04-13 00:43
Send me the log file

**Comment by CodyBerenson** [comment] 2020-04-13 01:14
@JPH71 
Here's the log
[com.plexapp.agents.WayBig.log](https://github.com/CodyBerenson/PGMA-Modernized/files/4467558/com.plexapp.agents.WayBig.log)

**Comment by JPH71** [comment] 2020-04-13 01:35
@j-ktz
@CodyBerenson

i have just tested it against gaydvdempire and it works
(Kink Clips) - Jessie Colter & Brock Avery Vs Seth & Billy Santoro - Live
Fight (2019)
i will check it against WayBig

**Comment by JPH71** [comment] 2020-04-13 01:36
Just checked your log and it doesn't even search for the file...

**Comment by JPH71** [comment] 2020-04-13 01:37
I will however, have to look at the code around the collections in
gayDVDempire.... its returning an error in the log

**Comment by JPH71** [comment] 2020-04-13 01:40
can you send me the link on waybig for the file
(Kink Clips) - Jessie Colter & Brock Avery Vs Seth & Billy Santoro - Live
Fight (2019)

**Comment by j-ktz** [comment] 2020-04-13 01:44
I got the GayDVDEmpire one working. Forgot a hyphen. The WB one still fails tho

**Comment by JPH71** [comment] 2020-04-13 01:48
send me the waybig link.... i cant find the scene on waybig

**Comment by JPH71** [comment] 2020-04-13 01:54
@j-ktz.... could you send me the waybig link so that i can check why its
failing......

**Comment by CodyBerenson** [comment] 2020-04-13 02:19
@jph71 
i dont know what youre smoking but i want some.    lol. i have no idea whatfile youre matching to. he was asking about a corbin fisher file from 2006. the link is in the top of the thread. 

brock avery...billy santoro....wtf???  lol lol lol

my brother, step away from the pipe for a bit...

**Comment by JPH71** [comment] 2020-04-13 02:54
@codyberenson

we are all talking about this file -
(Kink Clips) - Jessie Colter & Brock Avery Vs Seth & Billy Santoro - Live
Fight (2019)

No wonder you just thought i was smoking wacky backy..... my conversation
history on this thread in google starts 2hrs ago when you @ed me
[image: image.png]

dumb dumb dumb......

**Comment by JPH71** [comment] 2020-04-13 02:54
hold fire on RadVideo.... just making some changes

**Comment by CodyBerenson** [comment] 2020-04-13 10:37
perhaps it is my github view.  But I see no conversation in the thread about this other file. But since the two of you are on the same wavelength, then all good  lol

**Comment by JPH71** [comment] 2020-04-13 11:07
I am confused... I was responding to both you and @j-ktz... Were you
talking about this live fight file or was there another file that failed to
get metadata on QC and/or WB?

**Comment by CodyBerenson** [comment] 2020-04-13 11:25
Pumpkin, i see no trace of a thread about a live fight file anywhere.  That is why i was confused and laughing at your response.  @j-ktz opened this thread about a Corbin Fisher file from 2006 that he couldn't match.  As I read and reread the thread, there's no mention anywhere about this live fight file until you mention it....but then he acknowleges....so, clearly some how, some way you two are in sync.  I have no idea how that could be, from the GitHub thread, but that doesn't matter.  As long as you two are in sync.  I don't need to be.  :)

**Comment by JPH71** [comment] 2020-04-13 11:53
Ah... So you were talking about another file when you asked what I
thought... I was wondering why everything was coming across disjointed...
GitHub seems to be rather weird as it forwards some emails in the thread to
my Gmail and doesn't do the others...
Maybe using the @ sign in the emails causes this....

Anyways... I am looking forward to scrapping IAFD, until I can find a way
to sort out gayVodclub and adultdvdmarketplace... Adrian seems to have gone
into hibernation as he hasn't replied whether he can help or not...

If you find another good blog site let me know as it would be good to get
at least 5 sites for the scenes..

Have you tried radvideo yet?

**Comment by CodyBerenson** [comment] 2020-04-13 11:59
LOL.  That still doesn't explain that live fight file, cause its no where in any of the threads.  LOL.  Anyway, I have a number of films queued up.  I'll specifically throw them only at RAD and will let you know.

**Comment by JPH71** [comment] 2020-04-13 12:07
true.... as it comes up after you mentioned me in the thread........

the new cigarettes i bought... i blame them :-)

**Comment by CodyBerenson** [comment] 2020-04-13 12:09
ok, buttercup.  where in the thread do i ever mention a live-fight file?  please include a pointer or screenshot.

**Comment by j-ktz** [comment] 2020-04-13 12:28
Sorry for the confusion @JPH71 @CodyBerenson. I made a comment about another post note matching and then realized I was an idiot and forgot a hyphen, so I deleted the comment. But @JPH71 probably still saw the comment in his email maybe?

**Comment by CodyBerenson** [comment] 2020-04-13 12:36
Ahhh!  Mystery Solved!  LOL

NO worries!!!  Personally, I'm a bit new to GitHub so I'm just trying to make sure everything reconciles and that i wasn't misunderstanding its functionalities.

Very glad it is working for you.  I've been there on a thousand occasions, forgetting a requisite hyphen, or a parentheses, or...  LOL

@jph71 don't forget to look at the Corbin Fisher file, first post in this thread.  :)

**Comment by JPH71** [comment] 2020-04-13 15:41
I can't see the Corbin fisher file... I got the thread at the point from
the screen shot I sent you.. j-ktz mentioned the live fight title soon
after and I assumed that was what you had being talking about...
Send me the Corbin fisher title and I will check it out on QC and waybig
... I gather it's not working on those two...

**Comment by j-ktz** [comment] 2020-04-13 15:44
@JPH71 This won't match on WB.
<img width="557" alt="screenshot 2020-04-12 at 7 54 21 PM" src="https://user-images.githubusercontent.com/59346628/79134684-192cbb00-7d7c-11ea-9975-5b4484addb90.png">
https://www.waybig.com/blog/2006/01/18/cades-workout-corbinfisher/

**Comment by JPH71** [comment] 2020-04-15 01:35
@CodyBerenson

I have made changes to waybig to solve the issue with the file
(CorbinFisher) - Cade's Workout (2006)
Waybig now drops the first word of the title if it contains any apostrophe so that it searches for Workout as the title..

It builds 4 search strings - and uses each of these in sequence until it finds the entry. I changed the sequence as thus to improve the speed

Studio: Title
Title
Studio: Title at Studio
Title at Studio
It now also searchs additional pages if the search returns more
I have improved logging so that the log files are easier to follow

Happy testing!
WayBig.bundle.zip

**Comment by CodyBerenson** [comment] 2020-04-15 11:01
You are incredible.  

Alright, i'll start some testing.  May take me a while to find enough suitable test cases, but i'll let you know.  Thanks all.

**Comment by CodyBerenson** [comment] 2020-04-15 12:17
@JPH71 

Bad results.  I queried WayBig for a dozen scenes with ' in the first name.  I also took the six most recent scenes to make sure that the agent still works. 

Nearly none of them matched. Including Cade's workout.

Here's what matched (note, there are two with ' in first word):
(American College Sex) - Dane’s POV Fuck (2018)
(American College Sex) - Dave’s Poolside Fuck (2017)
(MASQULIN) - Dato Foland Fucks Anteo Chara in ‘Russian Ballet’ (2020)
(TimTales) - Anton PJ Fucks Rico Fatale (2020)
(YesFather) - Father Fiore Fucks Mason Anderson in ‘Altar Training’ (2020)
(Military Classified) - Shepherd Fucks Rob (2020)

Here's what did not match (note, there are two with no ' in first word):
(American College Sex) - Barron’s After Hours Massage (2020)
(American College Sex) - Beau’s Threeway Tease (Bareback) (2017)
(American College Sex) - Dane’s Lucky Afternoon (2020)
(Corbin Fisher) - Cade’s Workout (2006)
(Corbin Fisher) - Kai II (formerly Jacob Booker at GayHoopla) (2020)
(CorbinFisher) - Barron’s First Time (Barron Fucks Hugh) (Bareback) (2016)
(DirtyTony) - Dominick’s First Gay Blowjob (2010)
(DirtyTony) - Nick’s First Fuck (2010)
(Helix Studios) - Max’s First Time (Max Carter & Kyler Ash) (2012)
(MASQULIN) - Dato Foland Fucks Anteo Chara in ‘Russian Ballet’ (2020)
(NextDoorTwink) - Landon’s First (Jay Dubbs & Landon Terry) (2011)
(RaunchyBastards #175) - Street-Urchin Clutch Jerks Off in ‘Homeless Teen Has Nice Cock’ (2020)

So I revered to the master repository's version of WayBig.  All of the unmatched scenes now match, except Cade's workout.....

Back to the drawing board.

**Comment by CodyBerenson** [comment] 2020-04-15 12:26
I'm going to remove the bundle from the thread so no one grabs it by accident.

**Comment by JPH71** [comment] 2020-04-15 13:24
I will look at it again - I tested it against cade's workout and an old tim
tales which did not have any apostrophe's in it...

I will use your list

Cheers

Jason

**Comment by JPH71** [comment] 2020-04-15 23:21
@CodyBerenson 

I threw all the titles you gave me against it and it matched them all.
We now should not have to worry about curvy quotes in waybig, they were not working before because i ran a strip diacritics routine before looking at the apostrophes and ofcourse they had being removed....
the nextdoor one would not update the posters - its one of the strange ones that did not have a width attribute attached to it - so i use a default width of 600 for it...
I also had a few very stupid errors - one made an infinite loop!!!! very beginner coding error...
but the weirdest thing about waybig search is its handling of paratheses they can not be url encoded!

here it is
[WayBig.bundle.zip](https://github.com/CodyBerenson/PGMA-Modernized/files/4484127/WayBig.bundle.zip)

**Comment by CodyBerenson** [comment] 2020-04-16 11:17
@JPH71 
Ok, I'll test and report back.  :)

**Comment by CodyBerenson** [comment] 2020-04-16 11:59
@JPH71:  I took the 12 scenes with ' in the first word, and the six most recent blogged scenes on waybig.  Out of 18 scenes, 17 match.  Cade's Workout...the root cause of all of this...still does not match....it matched for you???

I noticed the nextdoor not having a poster yesterday, but its so rare that it happens i don't stress about it because i use https://cdn.vigue.me/unsafe/0x0:600x900/<posterURL> and manually add.

That said, I couldn't tell from your note above whether you introduced a fix or not re: the poster, because it still didn't add.

**Comment by CodyBerenson** [comment] 2020-04-16 12:02
Here's the log for Cade's Workout
[com.plexapp.agents.WayBig.log](https://github.com/CodyBerenson/PGMA-Modernized/files/4486888/com.plexapp.agents.WayBig.log)

**Comment by CodyBerenson** [comment] 2020-04-16 15:14
This Cade dude is pissing me off.  If if were Cade Maddox I'd jump thru hoops....

**Comment by j-ktz** [comment] 2020-04-16 16:14
😂😂😂😂😂

**Comment by JPH71** [comment] 2020-04-16 16:47
Cade matched for me.. I made sure it did before I sent it too you.. the
first time it did not work as it had the curly apostrophe.. so when that
got sorted.. I worked on the next door twink ang got it to work...
Do this match them separately and send me the each ones log..
There 8s no way this bloody scrapper is not going to work...
I am back home in England.. good internet for a change x

**Comment by CodyBerenson** [comment] 2020-04-16 18:00
When i changed the curly single quote to a hyphen, both matched and returned posters.  (Next door had matched before, but but didn't return a poster). 

So now I'm confused....single curly quotes....we have to change them to hyphens again?  

Its ok if we do, I was very used to it...I will just need to update the read-me again.  :)

**Comment by JPH71** [comment] 2020-04-16 18:09
No curly quotes were never meant to be changed to hyphens - we used to
change them to straight quotes....
I am just about to test the twinky and cade...
give me five minutes...
I want waybig to be like fagalicious...

**Comment by JPH71** [comment] 2020-04-16 18:40
Just looking at your log file and its format is completely different from
mine.
my log files are situated in this folder:

C:\Users\<username>\AppData\Local\Plex Media Server\Logs\PMS Plugin Logs

where are yours situated.... the logs I have give you step by step
instruction on what fields it's filing etc...

I will send you an example of my waybig log file....

**Comment by JPH71** [comment] 2020-04-16 19:26
@CodyBerenson 

I did a jason and introduced an error in the retrieval of the summary metadata item.
Here is the corrected version.

Jason, sorry about this wasting of your time. yesterday I was so pleased to see it pull in the pictures that I forgot to look at all the other stuff, which i had changed when I tidied up the code...

[WayBig.bundle.zip](https://github.com/CodyBerenson/PGMA-Modernized/files/4489355/WayBig.bundle.zip)

**Comment by CodyBerenson** [comment] 2020-04-16 19:38
My buttercup has now cracked into a million pieces.  I'm worried about his mental health.

RE:  log file.  was that question for me?  If so, yes, same directory.  It looks just like the log i posted in the beginning of this thread and just like the typical logs.  you have me so very confused.

re: the new waybig bundle...i'll retest the 12 plus pull in a new 6.  i'll let you know. right now my plex is matching a couple hundred films that I just dropped...so it may be a while.

**Comment by JPH71** [comment] 2020-04-16 22:37
your log file looks totally different from mine - mine shows the search
agent and the update agent and all the data it gets off the web page -
yours seems to be full of debug statements and calling loads of php....
hence why i asked if we were using the same log file...
look at the contents and you will see what i meant.

i think i have found a new website to scrape after iafd... i will take a
look at it before asking you to raise an issue...
Its great to be back home in England!


Cheers

**Comment by CodyBerenson** [comment] 2020-04-16 23:02
@JPH71 
Hi Jason,

Welcome home!  Glad you're safe and sound!  

Re: logging, perhaps we have the "Enable Debug Logging" preference set differently from each other?  

Re: testing...The updated code is Matching good.  30 files (12 from the above, and the most recent 6 on WayBig, and 12 that I had queued up).  All matched, 30 for 30. 

But...the posters....Question:  did you make a logic change to the image cropper?  It is cropping oddly now.  I'm having to fix the posters myself...Take a look at these scenes, you'll see what i mean:

1. (Naked Sword Originals) - Cade Maddox Fucks Jarret Moon in ‘BARE: Big Dicks and Bubble Butts, Scene 1’ (2020).mp4

2. (Next Door RAW) - Dalton Riley Fucks Tristan Hunter in ‘Rim This Hole!’ (2020).mp4 

3. (CockyBoys QUICKIE) - Austin Wolf Fucks Cory Kane (2020).mp4 

4. (Hot House) - Quin Quire Fucks Johnny Ford in ‘Making Moves, Scene 2’ (2020).mp4 

xoxo

Cody

p.s.  I found a blog, but I don't love it.  I was indexing Island Studs and it had a couple scenes that weren't on the other three.  I'm going to check it out a little more before I recommend it to you.

**Comment by JPH71** [comment] 2020-04-17 21:57
@CodyBerenson 

Made the relevant changes to waybig... a bit of code which i thought would work failed and left the default width to 600px hence the slicing of the right hand side of the document.

I have also reworked all the code that decides whtehr its going to use the original or thumbor or script cropped image and improved the logging around here. I will have to replicate this in fagalicious and queer click - but i will let you test this one first before i race ahead as i am prone to...

I have removed the preference for logging so that when someone has a problem we can always ask them for the log and will have all the issues listed on why it has failed and where the failure occured.

here is way big:
[WayBig.bundle.zip](https://github.com/CodyBerenson/PGMA-Modernized/files/4495414/WayBig.bundle.zip)

**Comment by CodyBerenson** [comment] 2020-04-17 22:54
@JPH71 

Well done.  I tested the most recent 8 scenes on WayBig.  Posters are looking the way they should!

There was one however that wouldn't match, and its a scenario that i've never run across there is an @ symbol in the title.  However, that title is on QC, so folks can get the match there.  LOL.  

However, after testing this I realize that you want me to also test that the VB script fire....?    So, i'll go test that now.

Cody

p.s.  knowing you're a perfectionist, here's the new oddity.  please don't fix.  i'll tell them to use QC.
(Corbin Fisher) - Zander Fucks Mitch (a.k.a. Ayden @ SeanCody) (2020).mp4
https://www.waybig.com/blog/2020/04/17/corbin-fisher-zander-mitch-ayden-seancody/

**Comment by CodyBerenson** [comment] 2020-04-17 23:02
@JPH71 

I set the thumbor to fail, and retested the 8 scenes.  I expected one not to match, and it didn't (see the @ comment above.  Of the remaining 7:
1.  the script fired off for 6 of the 7 and cropped posters
2.  one of the waybig posters was exactly the correct size, so it imported it in

Well done!  Is it ok to close this issue?  After all, Cade's workout now matches perfectly fine.  

xoxo

Cody

Enjoy your weekend!

**Comment by JPH71** [comment] 2020-04-18 00:06
let me sort the @sign and send that in

**Comment by JPH71** [comment] 2020-04-18 00:56
@CodyBerenson 

Sorted the @ sign - just had to reverse the url encoding on this character like i had to for the brackets ()

Here it is:
[WayBig.bundle.zip](https://github.com/CodyBerenson/PGMA-Modernized/files/4495771/WayBig.bundle.zip)

**Comment by CodyBerenson** [comment] 2020-04-18 18:03
@JPH71 

Happy Saturday bad boy!  The @sign scene matches perfectly.  

Now I'm pulling my hair out.  One of the test files with a tricky name, which I could swear matched perfectly yesterday, I can't get to match today....whether I use the most recent bundle or revert.  Can you see if you can get this to match?  You'll notice two colons in the title...which I could SWEAR I sorted out in naming the file and it matched.  

https://www.waybig.com/blog/2020/04/15/twink-top-new-recruit-chapter-1-tom-bentley-tops-agent-dani-robles/

**Comment by JPH71** [comment] 2020-04-18 19:33
I will take a look in 20 minutes... Keep the problems coming, so we can
sort out this scrapper...
At least we no longer have to change curly apostrophes to straight ones now
👍👍👍

**Comment by CodyBerenson** [comment] 2020-04-18 19:42
si senor.  but, i don't think there's a problem with the scraper.  i think the problem is with me having a brain fart and forgetting how to properly name this file.  This is a good example for the readme.

**Comment by JPH71** [comment] 2020-04-18 20:24
@CodyBerenson 
There was a little problem, Commas also can not to be used in their URL format %2C... so just like colons and brackets have to be replaced...

next thing if the search string goes over 50 characters - it refuses to work... so had to trim that wee heifer down...

here it is!
[WayBig.bundle.zip](https://github.com/CodyBerenson/PGMA-Modernized/files/4497569/WayBig.bundle.zip)

**Comment by CodyBerenson** [comment] 2020-04-18 23:25
@JPH71 

The double colon (sounds dirty?) scene matches perfectly.  I have a bunch more to throw at it to make sure nothing broke....will report back.

xoxo

**Comment by CodyBerenson** [comment] 2020-04-19 03:47
@JPH71 

I know...i'm driving you crazy!  didn't we sort out exclamation points in titles?  My testing for a couple can't match....

1. (FraternityX) - HALF STRAIGHT! (2019)
2. (FraternityX) - Yo Bro, Get That Homo! (2020)

**Comment by JPH71** [comment] 2020-04-19 23:21
@CodyBerenson 

Hi Cody

That's no problem at all, with this change hopefully we have got most of the problems solved.
I also took the opportunity to sort out fagalicious with the new cropping code. Then I tested it with this file **(CutlersDen) - Donnie Argento gets fucked raw by Cutler X (2019)**
and found out that it was not able to scrape the summary, so I have amended that code also. 
And also took the opportunity to bring the multipage search to work like it is doing in wayBig which was more efficient.
And lastly did my best to sort out cast and genres... fagalicious mixes this two up - so i started finding words like solo, bareback etc listed as cast... so i improved on that code. Unfortunately for the file i have enbolded above the actors are not in the list fagalicious displays so it correctly comes back with no cast members....

So here they are!
[Fagalicious.bundle.zip](https://github.com/CodyBerenson/PGMA-Modernized/files/4500478/Fagalicious.bundle.zip)
[WayBig.bundle.zip](https://github.com/CodyBerenson/PGMA-Modernized/files/4500479/WayBig.bundle.zip)

**Comment by CodyBerenson** [comment] 2020-04-20 11:23
@JPH71 
Happy Monday Pumpkin!

The WB fix matched the two scenes above with exclamation points, as well as an additional (and complicated) test case I found:

(FraternityX) - TAG THAT ASS! (Charlie Pattinson, Cooper Steel, Ian Greene, Junior Fernandez, Liam Rydell, Miles Taylor, Tucker Reece and Tyler White) (2017).mp4 

Well done!

I've got a bunch of test files to throw at both WB and F....and if all good, I'll push to the repository.  :)

xoxo

**Comment by CodyBerenson** [comment] 2020-04-20 12:05
@JPH71 
Hmmmmmm...I don't think I've seen this before.  I dropped about 45 files....100% match!  Yay!  Posters are perfect!  Yay!  But, for about 15 of the files, there's some weird code at the beginning of the description (easy enough to manually delete....but I wanted you to see:

flowplayer("player", "https://www.waybig.com/blog/flwplayerfiles/flowplayer.commercial-3.2.7-1.swf", {
clip: {
// stop at the first frame and start buffering
autoPlay: false,
autoBuffering: false
}
});

![image](https://user-images.githubusercontent.com/40373801/79749652-948eef00-82dd-11ea-9b0c-c5ab67f0c1ad.png)

**Comment by JPH71** [comment] 2020-04-20 20:27
easy enough to fix - which agent did this?

**Comment by JPH71** [comment] 2020-04-20 20:27
Check the tagline - it will tell you...

**Comment by CodyBerenson** [comment] 2020-04-20 20:28
sorry, i meant to include.  they're all waybig

**Comment by JPH71** [comment] 2020-04-20 20:28
just seen it - waybig... doh
i will sort it out now

**Comment by JPH71** [comment] 2020-04-20 20:46
All done....
I used a function to escpape the regex... didn't work as expected...
all corrected now

Let me know the blog you were talking about the other - i took a look at queerpig but it does not have any damn artwork.... very annoying....

Here it is!
[WayBig.bundle.zip](https://github.com/CodyBerenson/PGMA-Modernized/files/4506065/WayBig.bundle.zip)

**Comment by CodyBerenson** [comment] 2020-04-20 21:23
Yup, that clears it up.  I'll do a bit more testing but at this point I think I can push to the master repo....both WB and F.

The blog site is https://www.roughstraightmen.com/

No Posters per se like WB, F, and QC, but does have artwork that could be cropped....

**Comment by CodyBerenson** [comment] 2020-04-21 14:24
@JPH71 

Updated and testied WB and F have been pushed to the master repository.  I'll close this issue  in a couple of hours.  

Well done!  As always, terrific collaborating with such a dedicated genius.  :)

**Comment by JPH71** [comment] 2020-04-21 15:12
blush blush blush... i am going mahogany!

**Comment by CodyBerenson** [comment] 2020-04-21 15:17
LOL.  

Then maybe its time to challenge you again!  LOL.  This next scene is the easiest of easy...no special characters....but will not match.  Any thoughts?  (AND DO NOT FIX!!! I will just use IAFD and build a nfo!)

https://www.waybig.com/blog/2020/03/10/broke-straight-boys-james-dawn-takes-inch-casey-owens/

(Broke Straight Boys) - James Dawn Takes Every Inch Of Casey Owens (2020).mp4

**Comment by JPH71** [comment] 2020-04-21 16:07
Already done - it was because the 50th character was a % sign
corrected....

**Comment by JPH71** [comment] 2020-04-21 16:12
Already done - it was because the 50th character was a % sign
corrected....
[WayBig.bundle.zip](https://github.com/CodyBerenson/PGMA-Modernized/files/4511153/WayBig.bundle.zip)

**Comment by CodyBerenson** [comment] 2020-04-21 17:04
STOP IT!  LOL.  You're just encouraging me to find the one-in-a-thousand WB oddities that stumps the Agent.  LOL.

OK, I'll give it a go and report back.

**Comment by j-ktz** [comment] 2020-04-21 17:44
Thank you both for all your hard work. Should the new bundle on the main page fix the Cade’s Workout issue?

**Comment by CodyBerenson** [comment] 2020-04-21 17:47
@JPH71 
This bundle fixed it.  I threw another 82 files at it and 100% match.  I'll push to the master repository.  Sorry I can't come up with anything else at the moment to stump you.

@j-ktz 
The main page bundle fixed that dickhead Cade's issue.  However, if you wait about 5 minutes, i"m going to push another update and will close this issue.  

Cheers!

**Comment by CodyBerenson** [comment] 2020-04-21 17:49
Master Repository has been updated.  Cheers all.

**Closed** 2020-04-21 19:43 UTC
Labels: bug

**Comment by JPH71** [comment] 2020-04-21 20:21
👍👍
