### ISSUE TITLE
IAFD has stopped returning Actors, Directors with All PGMA Agents

### ISSUE THREAD

**Issue by CodyBerenson** [CodyBerenson/PGMA-Modernized#85] opened 2021-04-03 21:58 UTC
In the past 24 hours, IAFD has stopped working with our agents.  The logs throw errors for every film, actor, director search from Plex....even though one can manually perform the exact same searches from a browser.  

Jason is looking into it.  Stay tuned.

**Comment by Teda1** [comment] 2021-04-05 04:47
Is the error a 403? I've been running into 403's ever since I started running my server in an UnRAID docker container. On my windows server I have been able to get around this by specifying a `User-Agent`. However the `User-Agent` does not resolve the issue in my UnRAID docker container.

**Comment by JPH71** [comment] 2021-04-05 14:28
Yes it's a 403...

**Comment by Teda1** [comment] 2021-04-06 04:17
Okay, I've been looking into this as well when I get free time. It will be interesting to see what the solution ends up being.

**Comment by Teda1** [comment] 2021-04-06 05:27
I've tested and confirmed that this issue can be avoided by using the cloudscraper api to bypass Cloudflare on the site.
https://pypi.org/project/cloudscraper/

**Comment by JPH71** [comment] 2021-04-06 06:51
Cheers @Teda1

I will look into the cloudscraper api.....

I wrote this little script and changed the headers and managed to get the
correct response code 200

import requests
myString = '
https://www.iafd.com/results.asp?searchtype=comprehensive&searchstring=Friendly+Fire+11
'
headers = {'User-Agent':
'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.11 (KHTML, like
Gecko) Chrome/23.0.1271.64 Safari/537.11'
,
           'Accept':
'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
           'Accept-Charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.3',
           'Accept-Encoding': 'none',
           'Accept-Language': 'en-US,en;q=0.8',
           'Connection': 'keep-alive'}
r=requests.get(myString, headers=headers)
print(r.status_code)

But I tried to implement it in the agent and it went back to a bloody 403,
I have done the imports in the main agent __init__.py for the requests and
html - hence why there is a tree variable rather than the old html variable
to hold the page contents and perform xpath operations on... I even added a
timeout.... I can not see why this does not work as yet...

def getIAFD_URLElement(self, myString):

''' check IAFD web site for better quality actor thumbnails
irrespective of whether we have a thumbnail or not '''
    myException = ''
    for i in range(2):
        try:
            self.log('IAFD  :: Web Address: %s', myString)
            headers = {'User-Agent':
'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.11 (Ktree, like
Gecko) Chrome/23.0.1271.64 Safari/537.11'
,
                       'Accept':
'text/tree,application/xtree+xml,application/xml;q=0.9,*/*;q=0.8',
                       'Accept-Charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.3',
                       'Accept-Encoding': 'none',
                       'Accept-Language': 'en-US,en;q=0.8',
                       'Connection': 'keep-alive'}
            page = requests.get(myString, headers=headers, timeout=20)
            self.log('IAFD  :: Requests Return Code: %s', page.status_code)
            tree = html.fromstring(page.content)

            try:
                searchQuery = tree.xpath(
'//a[text()="See More ***@***.***')[0].strip()
                if searchQuery:
                    searchQuery = IAFD_BASE + searchQuery if IAFD_BASE not
in searchQuery else searchQuery
                    self.log(
'SEARCH:: Loading Additional Search Results: %s', searchQuery)
                    page = requests.get(searchQuery, headers=headers, timeout=
20)
                    self.log('IAFD  :: Requests Return Code: %s', page)
                    tree = html.fromstring(page.content)
            except:
                self.log('IAFD  :: No Additional Search Results')
            return tree
        except Exception as e:
            myException = e
            continue
    # failed to read page
    raise Exception('Failed to read IAFD URL [%s]', myException)

**Comment by Teda1** [comment] 2021-04-07 00:30
Something like the following should get the job done. The cloudscraper module will only seems to support Python 3 though.
```
import cloudscraper
import requests
from lxml import etree

scraper = cloudscraper.CloudScraper()

headers = {}
headers['User-Agent'] = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36'
scraper.headers.update(headers)
req = scraper.request('GET', 'https://www.iafd.com', data=None)
tree = html.fromstring(req.content)
```

If you need a fix for python 2 you could try https://dev.to/mesadhan/python-bypass-anti-bot-page-and-scrape-it-1aa6

**Comment by JPH71** [comment] 2021-04-07 07:08
PLEX WORKS ON PYTHON 2.7

**Comment by JPH71** [comment] 2021-04-07 07:08
sorry bout the caps lock

**Comment by Teda1** [comment] 2021-04-07 14:25
No problem! I know Plex runs on python 2.7 but it seems like the agents will still run as long as your agent provides the modules in the shared libraries directory. It’s not completely clear to me how though. The fix I posted earlier works just fine with my agent. You can also look at this code from the PhoenixAdult plugin. Their code also uses the cloudscraper module: https://github.com/PAhelper/PhoenixAdult.bundle/blob/master/Contents/Code/PAutils.py

**Comment by CodyBerenson** [comment] 2021-04-07 15:56
@Teda1 Sorry, far less technical than you and Jason...just trying to follow.  Are you saying that the Phoenix Adult Plugin's  isn't viable?  https://github.com/PAhelper/PhoenixAdult.bundle/blob/master/Contents/Code/PAutils.py

**Comment by Teda1** [comment] 2021-04-07 16:25
The implementation in the PAutil file is viable. I was just correcting my comment to say that I was wrong in stating that python 3.x was required.

**Comment by JPH71** [comment] 2021-04-07 18:13
@Teda1 - you are a star...

Thank you so very much for your help!

Would you mind me having a look at your agent too??

Next if you come across another website that holds porn actor information
let me know - It would be a good idea to have an alternative...

Cheers

Jason

**Comment by Teda1** [comment] 2021-04-07 18:50
My agent is just a forked version of the PA agent that was modified to sync with some older agents I wrote a while back. The Helper module I wrote which references iafd does not live in the PA agent so I was not using the Cloudflare bypass code in PAutil. I didn’t realize Cloudflare was the cause of the 403 error until I looked at the HTML response content.

No problem, if I come across any more I’ll let you know. From what I’ve seen so far PA is the most extensive. There are some new database sites that sync all movie data across various porn sites similar to what data18 used to do. If you want to take a look at them the sites are https://metadataapi.net/ , and https://traxxx.me/updates/latest/1. I’ve been toying around with the idea of writing a new agent for one of them if the desire to have one site that already does most of the work for me reignites.

**Comment by JPH71** [comment] 2021-04-07 19:21
kisses!

**Comment by fivedays555** [comment] 2021-04-10 23:13
https://github.com/jychp/cloudflare-bypass

Maybe worthing looking to.....
Thanks for making this great agent.

**Comment by JPH71** [comment] 2021-04-11 13:13
Many thanks @fivedays555 and for the appreciation too!

**Comment by fivedays555** [comment] 2021-04-12 00:35
I think for the same reason, the Fergalicious agent stops working as well. It's using Cloudflare as well.
A temporary solution would be adding the header with cookies together, but it will expire in some time.

**Comment by codeanator** [comment] 2021-04-13 17:21
I managed to fix this issue using cloudscraper (inspired by PAUtils) from PhoenixAdult.
I finalize my testing and I'll PR the changes soon

**Comment by codeanator** [comment] 2021-04-13 18:58
IAFD scraper fixed - as well as other iads.py bugs fixed in PR #87

**Comment by CodyBerenson** [comment] 2021-04-13 23:53
Testing now.  :)

**Comment by CodyBerenson** [comment] 2021-04-18 00:33
Hi folks,

Huge thanks to @codenator ...the IAFD Cloudflare issue has been resolved.  All of the agents have been updated with the fix.

**Closed** 2021-04-23 09:58 UTC
Labels: bug
