### ISSUE TITLE
WB and FG not pulling in posters

### ISSUE THREAD

**Issue by j-ktz** [CodyBerenson/PGMA-Modernized#15] opened 2020-04-22 13:35 UTC
I downloaded fresh new agents from the Code page yesterday and replaced them all and stopped/started server. WB and FG files will put in all metadata except posters. I checked and I am still using https://cdn.vigue.me/unsafe in the agent settings. Is that still correct?

**Comment by CodyBerenson** [comment] 2020-04-27 11:24
@j-ktz @JPH71

GitHub mistakenly flagged the site in their automated scripts they run where they're looking for fake "spammy" accounts.  Sorry to have been out of touch.  Are you still having issues?  If so, can you provide your logs for Jason?

In the meantime, he's been very busy creating new agents/updating existing agents, so he's been giving me quite a backlog of testing.  If he weren't such a genius, I'd smack him silly for "fixing" things that aren't broke.  LOL.

Cody

p.s.  no injecting, drinking, or gargling with disinfectant, please.   If you insist on introducing disinfectant into your body, please do so by incorporating into your marinades and brines.  Disinfectant, and direct sunlight, is only safe when incorporated as part of a well balanced meal.

**Comment by JPH71** [comment] 2020-04-27 11:43
@CodyBerenson
With this lockdown - i would give up my lower cheeks for a smack!
:-)

**Comment by JPH71** [comment] 2020-04-27 12:35
quick question - i noticed that GEVI also gives scene breakdowns like
IAFD...
would you like this scrapped?

**Comment by JPH71** [comment] 2020-04-27 18:38
> I downloaded fresh new agents from the Code page yesterday and replaced them all and stopped/started server. WB and FG files will put in all metadata except posters. I checked and I am still using https://cdn.vigue.me/unsafe in the agent settings. Is that still correct?

@j-ktz - send me the logs - or at least an example of the file you are trying to scrape - otherwise I won't be able to find the problem!

**Comment by j-ktz** [comment] 2020-04-27 18:58
Hello Boys! I was worried we were gonna lose each other and I was gonna have to try and hunt you both down on social to try and put this thing back together. @JPH71, I'll send you logs when I can! It was every WB and FB poster. All data was coming in except posters. I know that isn't helpful so I'll send logs ASAP. Good to hear you're both okay!

**Comment by j-ktz** [comment] 2020-04-27 19:44
@JPH71 Here's an example I just did for FG. It pulls in all metadata great except poster. Logs attached. 
<img width="779" alt="screenshot 2020-04-27 at 3 43 37 PM" src="https://user-images.githubusercontent.com/59346628/80413741-f0d5ae00-889d-11ea-9d9c-b0b1e4bf5ccf.png">
<img width="534" alt="screenshot 2020-04-27 at 3 43 32 PM" src="https://user-images.githubusercontent.com/59346628/80413743-f0d5ae00-889d-11ea-8de1-a7171c9a77c3.png">
[Archive 2.zip](https://github.com/CodyBerenson/PGMA-Modernized/files/4541719/Archive.2.zip)

**Comment by CodyBerenson** [comment] 2020-04-27 22:14
@JPH71 
Re: IAFD scene info, It would be terrific if you could pull in the synopsis first, new paragraph, scene info. thats what i do when i manually create the xml

**Comment by JPH71** [comment] 2020-04-28 13:28
@j-ktz, are you on a windows machine??
As it is failing to get the %TEMP% folder, if not I will have to make a
change to the scene agents.....
there is an error in the logic....
damn!

**Comment by JPH71** [comment] 2020-04-28 13:55
@j-ktz
I have made the changes to Fagalicious to enable the posters to work - I realised that the same error would be in the other two as it was looking for an environment variable that would not be on a non-windows machine.From what I can remember you are using a MAC???Test to see if these work on your MAC
@CodyBerenson 
Just in case I haven't effed anything else up - could you test that they work on Windows based machine.Once I have written python code to deal with the cropping, this functionality will not be restricted to windows machines only...

Cheers
Jason

here are the 3 bundles
[Scene Bundles.zip](https://github.com/CodyBerenson/PGMA-Modernized/files/4546174/Scene.Bundles.zip)

**Comment by CodyBerenson** [comment] 2020-04-28 15:10
I'm having problems with QC and F.  and , just with version control in general.  tooooo many updates flying around. We need to get back on the rails.

**Comment by CodyBerenson** [comment] 2020-04-28 15:12
strike that.  QC isn't working.  And now I don't know which version to revert to to see if it works, because there are so many in the emails.  ARGH!

**Comment by CodyBerenson** [comment] 2020-04-28 15:14
QC files that don't work:

(NextDoorStudios) - Evan Landers and Tannor Reed (2020).mp4
(Men.com) - Colby Tucker and Paul Canon (2020).mp4

**Comment by CodyBerenson** [comment] 2020-04-28 15:19
I removed the bundles from the earlier thread.  At this point I don't know what to do other than to close this issue, open a new issue that is specific to non windows machines. 

I hadn't tested the all-bundles email, so i don't know if the broken QC is in what you just fixed, the previous bundle, etc.

**Comment by CodyBerenson** [comment] 2020-04-28 15:23
The All Bundles QC didn't work on these files either.

**Comment by CodyBerenson** [comment] 2020-04-28 15:26
hold up.  in your email musing about possible improvements to agents, you discuss removing ".com"....is there a change to the naming rules introduced now?

**Comment by CodyBerenson** [comment] 2020-04-28 15:32
The QC bundle in the master repository matches these files.  You have a version control issue my friend.   Somewhere you fixed something...not relating to j-ktz's issue...that broke the matching.  I'll test F now.

**Comment by CodyBerenson** [comment] 2020-04-28 15:48
I took the 8 most recent F scenes, and all match.  I'll test WB now and then more indepth QC.

**Comment by CodyBerenson** [comment] 2020-04-28 16:02
I took the 12 most recent WB scenes and all match.  Indepth testing QC now

**Comment by JPH71** [comment] 2020-04-28 16:07
> hold up. in your email musing about possible improvements to agents, you discuss removing ".com"....is there a change to the naming rules introduced now?

I was just thinking of it as an enhancement - i have not made any changes......

**Comment by JPH71** [comment] 2020-04-28 16:08
> I'm having problems with QC and F. and , just with version control in general. tooooo many updates flying around. We need to get back on the rails.

Shit - I forgot to update the version numbers - let me do that after testing QC - so that we have everything in alignment...

**Comment by CodyBerenson** [comment] 2020-04-28 16:23
I took the 12 most recent QC files.  zero match.  here's the log.  

[com.plexapp.agents.QueerClick.log](https://github.com/CodyBerenson/PGMA-Modernized/files/4547155/com.plexapp.agents.QueerClick.log)

**Comment by JPH71** [comment] 2020-04-28 16:42
@CodyBerenson 

I have upped the version for QC, and corrected the error...
Both files you sent me to test with matched straight away.
Here is the bundle
[QueerClick.bundle.zip](https://github.com/CodyBerenson/PGMA-Modernized/files/4547249/QueerClick.bundle.zip)

@j-ktz 
You will need to test this on your MAC

**Comment by JPH71** [comment] 2020-04-28 16:42
When I get time - I will look at some python code to do what the vbScript code does.....

**Comment by CodyBerenson** [comment] 2020-04-28 17:10
What change did you make to F?  because, when testing a QC file (F is ordered higher in my priority than QC), it is churning and churning and churning, filling log after log after log.  Once it reaches 1,024 KB, it starts a new file its on file 7 now.

[com.plexapp.agents.Fagalicious.log.zip](https://github.com/CodyBerenson/PGMA-Modernized/files/4547380/com.plexapp.agents.Fagalicious.log.zip)

**Comment by CodyBerenson** [comment] 2020-04-28 17:13
10 minutes, and it is still churning building log files.

**Comment by CodyBerenson** [comment] 2020-04-28 17:20
I killed PMS, unchecked F, and then tested QC.   12 of the most recent files, all 12 matched.

Although the twelve test files for F matched....a non F file sent it off into neverland.  That's a Fail for now.

**Comment by JPH71** [comment] 2020-04-28 18:54
I made the same change to fagalicious that i did to waybig - near the
poster retrieval.....
This is the change i made today, Red is removed - Yellow is added
[image: image.png]

moved the lines in red to here
[image: image.png]

and to here for the background art
[image: image.png]

**Comment by CodyBerenson** [comment] 2020-04-28 19:46
LOL.  me asking you what change you made was rhetorical.  it wouldn't mean much to me.  F generated two dozen logs on one file, and would still be going if i hadn't killed it.  It is a problem.  Did you review the log?  Why did it keep trying and trying and trying and trying? There definitely needs to be a limit to the number of results it cycles through.

**Comment by JPH71** [comment] 2020-04-28 20:56
I am looking through the code now...

GEVI was erroring on some titles - when i threw a bunch of files at it - so
I have corrected it
the title it was failing on was (Titan Media) - Caught In the Act (2013)

**Comment by JPH71** [comment] 2020-04-28 21:00
What was the name of the file you were trying to match that kept churning???

**Comment by JPH71** [comment] 2020-04-28 21:04
looking through the log file - i am hoping it's this one Noir Male:
DeAngelo Jackson fucks Jacob Peterson in “Casting Couch”
<https://fagalicious.com/noir-male-deangelo-jackson-fucks-jacob-peterson-in-casting-couch/>

**Comment by CodyBerenson** [comment] 2020-04-28 22:19
No pumpkin, you are misunderstanding.  

I wasn't trying to match a scene on F.  I was testing QC.  QC is lower in priority so it has to go thru WB and F to get to QC.  It never got to QC because it churned endlessly in F.  The agents, I believe, need to have a set limit of titles they'll search thru before giving up.  The F agent churned and churned and churned, and built log after log after log.

The QC scene is 

(NoirMale) - DeAngelo Jackson.mp4

**Comment by CodyBerenson** [comment] 2020-04-28 22:29
So technically, all three agents you just posted match fine and retrieve posters, but I think its worth looking into the endless churn issue before releasing them as good-to-go.

**Comment by JPH71** [comment] 2020-04-29 00:48
Hi Cody
I found the error out - i was looking at the wrong bit of html when going for the next page - so it did page 1, then page 2 then went back to page 1.... ad infinitumThis has being sorted now - i tested it with (NoirMale) - DeAngelo Jackson and it found the correct number of results - 2 full pages and 1 title on the third page.

I then tested it on
`(NoirMale)` - DeAngelo Jackson fucks Jackson Reed in “BBC Massage” (2018)'

Jackson Reed does have a page on IAFD, but it would not pull his picture as his IAFD webpage lists him as Jackson Taylor, luckily the fagalicious uses this AKA name - so I manipulated that and managed to get his IAFD page.
All IAFD requests that return a null string are assumed as before to be genres.

here is the offending fagalicious - now sorted out, thanks for throwing that file at it as in most cases we don't find results going past 1 page...
[Fagalicious.bundle.zip](https://github.com/CodyBerenson/PGMA-Modernized/files/4549273/Fagalicious.bundle.zip)

**Comment by JPH71** [comment] 2020-04-29 01:41
@CodyBerenson 

Hi Cody
I found the error out - i was looking at the wrong bit of html when going for the next page - so it did page 1, then page 2 then went back to page 1.... ad infinitumThis has being sorted now - i tested it with (NoirMale) - DeAngelo Jackson and it found the correct number of results - 2 full pages and 1 title on the third page.

I then tested it on
(NoirMale) - DeAngelo Jackson fucks Jackson Reed in “BBC Massage” (2018)'

Jackson Reed does have a page on IAFD, but it would not pull his picture as his IAFD webpage lists him as Jackson Taylor, luckily the fagalicious uses this AKA name - so I manipulated that and managed to get his IAFD page.
All IAFD requests that return a null string are assumed as before to be genres.

here is the offending fagalicious and the other two scenes with the versions upped - now sorted out, thanks for throwing that file at it as in most cases we don't find results going past 1 page...

[3 SceneBundles.zip](https://github.com/CodyBerenson/PGMA-Modernized/files/4549387/3.SceneBundles.zip)

**Comment by CodyBerenson** [comment] 2020-04-29 12:13
lol.  The Ground Hog Day Agent.  Keeps living the same results page over and over.  

ok, i'll give them a test. and report back

**Comment by CodyBerenson** [comment] 2020-04-29 12:53
@JPH71 
Hi Pumpkin,

I threw the most recent 6 scenes for each of the three blogs, including the QC DeAngelo Jackson, scene.  100% match,

I have no means to test on a platform other than Windows, so @j-ktz will have to test on his Mac platform...although if memory serves, he doesn't use QC.

I am going to go ahead and push the code to the master repository....since we know the code that is there has issues with non-windows platforms, this code is preferable even if we haven't verified yet.

I'll wait a bit to hear back from @j-ktz before closing the issue.

Here's the package (i've been removing them from the thread until testing out ok):

[3.SceneBundles.zip](https://github.com/CodyBerenson/PGMA-Modernized/files/4551746/3.SceneBundles.zip)

**Comment by JPH71** [comment] 2020-04-29 13:13
Wait a wee bit....
Let me update all the version histories sorted for every bundle.
As I made changes to the get-IAFDActor fpr Fagalicious - I have to make it
for all the bundles and double-check that this change works...
I am feeling a bit guilty that I have being misusing you a wee bit....
I should have them done in 4 hours or so.....
Though - have you tried the new GEVI - in relation to the summaries and
ratings?? What do you think about the Scenes... should we retain them??
Cheers

Jason

**Comment by JPH71** [comment] 2020-04-29 13:14
@CodyBerenson
Wait a wee bit....
Let me update all the version histories sorted for every bundle.
As I made changes to the get-IAFDActor fpr Fagalicious - I have to make it
for all the bundles and double-check that this change works...
I am feeling a bit guilty that I have being misusing you a wee bit....
I should have them done in 4 hours or so.....
Though - have you tried the new GEVI - in relation to the summaries and
ratings?? What do you think about the Scenes... should we retain them??
Cheers

**Comment by CodyBerenson** [comment] 2020-04-29 13:54
I haven't looked at the film bundles.  I'll give GEVI a try now, see what you're referring to and report back.

**Comment by CodyBerenson** [comment] 2020-04-29 14:28
@JPH71 
I'm a little confused by your last message, please let me know if i'm not understanding correctly....I broke into separate thoughts.

1.  What specifically am I testing in GEVI?  I threw 3 files at it, it matched perfectly.  IT works, summaries and ratings are there....but it was working before so I'm not sure what I'm testing for.   

2.  Scenes.  Re: IAFD or re: GEVI?  In either case, I'm a fan for pulling the metadata that is there, and would be good when GEVI provides scene info, to include it in the description along with the summary.

**Comment by JPH71** [comment] 2020-04-29 14:50
In relation to GEVI...
The error that was there before was that it did not scrape the whole
summary, just the first paragraph...
I have added scenes and ratings..
As I have made changes to the getIAFDactor routine in fagalicious.. I will
for consistencies sake do it for all bundles soon
I prefer using the same hymn sheet at all times...
Either today or tomorrow I will get this done and update all the bundles...
In the meantime if you find anything wrong or want any changes let me know
and I will incorporate the corrections...

Cheers
Jason

**Comment by CodyBerenson** [comment] 2020-04-29 15:23
"I have added scenes and ratings"  Specifically to GEVI?  So are you saying that the GEVI scraper should pull in scenes?  If you are saying that (I am having trouble with your Cockney, Eliza Doolittle), it does not.  For example, this film has no summary but substantial scene info.  The agent pulled in nothing except ","

https://www.gayeroticvideoindex.com/V/0/65370.html

![image](https://user-images.githubusercontent.com/40373801/80613874-ca358580-8a0b-11ea-9840-483dff058e3a.png)

**Comment by JPH71** [comment] 2020-04-29 15:28
oh damn...
it did it for nearly 20 films i checked...
let me look at it now as I have finished work for the day!

**Comment by CodyBerenson** [comment] 2020-04-29 16:05
i'm using the GEVI that was part of the All-Bundles.zip you emailed.  Was there a different version?

**Comment by JPH71** [comment] 2020-04-29 16:06
@codyBerenson   
It really helps to send the correct version to you, i placed a copy in another directory before i went to far... and sent that one instead....
[GEVI.bundle.zip](https://github.com/CodyBerenson/PGMA-Modernized/files/4552856/GEVI.bundle.zip)

i need to get rid of the lines - View this scene at.....

**Comment by JPH71** [comment] 2020-04-29 16:23
@CodyBerenson   

Got rid of the View this scene at....
so if you havent started testing use this one instead
[GEVI.bundle.zip](https://github.com/CodyBerenson/PGMA-Modernized/files/4552969/GEVI.bundle.zip)

**Comment by CodyBerenson** [comment] 2020-04-29 19:09
ok pumpkin, i found one and tested and it worked perfectly.  i'll keep going but i'm slammed with work today...just wanted you to know.  :)

**Comment by JPH71** [comment] 2020-04-29 19:52
No hurry...
I am rather knackered so keeping my mitts of the editor tonight....

**Comment by CodyBerenson** [comment] 2020-04-29 20:36
knackered on....?  What was the poison tonight?

I actually think Treasure Island will be good tests. Many seem to have both description and scene info.  Fun fact:  TIM no longer is indexed on AEBN, or anywhere pretty much, so prior to your amazing GEVI agent, I was having to manually create the xml for new TIM titles.  LOVE the GEVI agent.  :)

**Comment by CodyBerenson** [comment] 2020-04-29 20:51
@j-ktz  please let us know if the updated code works for you on your Mac platform.  You can either get the updated code from the master repository or further up in this message.

Cheers!

**Comment by j-ktz** [comment] 2020-04-29 21:19
Hey boys! I just tested two files (one WB and one FG) and both worked great and pulled in posters. Thanks!

**Comment by CodyBerenson** [comment] 2020-04-29 21:29
@j-ktz great to hear.  thanks for hanging in there thru the github flub and trouble-shooting the root cause.  I'll close the issue tomorrow.

@JPH71 I tested a dozen TIM files on the updated GEVI.  Pulls in both description and scenes.  all matched.  Terrific job.  I'll push GEVI to the updated repository.

**Comment by JPH71** [comment] 2020-04-29 21:50
Had a long day at work today .... I need to have a drink before I get some
sleep...
GEVI is up to full scratch... Only update left is too get a cropper written
in python...
Yes GEVI is brilliant for treasure Island media... That's the next library
that I will scrape....

**Closed** 2020-04-29 21:58 UTC

**Comment by j-ktz** [comment] 2020-05-02 13:19
@JPH71 @CodyBerenson I'm having this issue again today and yesterday. It looks like it's happening on videos that have larger/longer posters. Could it be that https://cdn.vigue.me/unsafe/0x0:800x1200/ is down?

**Comment by JPH71** [comment] 2020-05-02 17:06
@j-ktz
I can't disgnose nowt without a log file...
Clear the agent log file, then run a Refresh Metadata on the video, then
send the log file to me...
Cheers
Jason

**Comment by CodyBerenson** [comment] 2020-05-02 20:41
@j-ktz 
The image cropper is up.  See for yourself:

https://cdn.vigue.me/unsafe/0x0:800x1200/https://fagalicious.com/wp-content/uploads/2020/04/Asher-Manny-SeanCody-1.jpg

Just to be sure, the address you use above isn't the address that you have in your settings.  In your settings for each Agent it should be:

https://cdn.vigue.me/unsafe

If you continue to have the problem, please open a new issue (don't post to a closed issue please), and attach your log as Jason asks.  There are only a handful of users at the moment, but as more and more join, they won't see issue traffic in the closed issues that they too may be facing.  Thanks friend!

**Comment by CodyBerenson** [comment] 2020-05-02 20:47
@j-ktz 
Also include the link for the scene.  While Jason combs thru the log, I'll test the scene for myself on my own system.

**Comment by j-ktz** [comment] 2020-05-03 12:42
@JPH71 I just tested again this morning and same issue with the poster not coming in, log attached! 

[com.plexapp.agents.Fagalicious.log](https://github.com/CodyBerenson/PGMA-Modernized/files/4570288/com.plexapp.agents.Fagalicious.log)

@CodyBerenson Sorry! I'll open a new issue going forward. Yesterday, when it was pulling in posters, I thought I'll just go to the URL myself, and paste in the image link after to get a cropped image but when I did, it said that it was down. Screenshot attached of what I was seeing. I could 1,000% be wrong. Just trying to diagnose myself and if all the other data was coming in and not the posters, and the URL was loading for me, thought maybe that might be where the issue was. Sorry I'm being a pain! Really appreciate all the work you both are doing.

Link to scene: https://fagalicious.com/fun-size-boys-caleb-anthony-legrand-wolf-bareback-chapter-1-dr-wolfs-office/

<img width="447" alt="screenshot 2020-05-03 at 8 39 50 AM" src="https://user-images.githubusercontent.com/59346628/80914485-dfffbf00-8d19-11ea-974e-5ceffd33ad86.png">

**Comment by JPH71** [comment] 2020-05-03 13:00
@j-ktz
You are right - it's not working for me either, I took the link
https://cdn.vigue.me/unsafe/0x0:585x877/https://fagalicious.com/wp-content/uploads/2016/10/Train-Me-Part-4-Bromo-2.jpg
and got the same error message

@CodyBerenson
Are you getting this error too?

**Comment by JPH71** [comment] 2020-05-03 13:03
@j-ktz
I am writing a routine in python - so that non windows users will also have
the ability for the agent to crop the posters if the cdn.vigue.me is not
working
bear with me - it will soon be done.

Jason

**Comment by j-ktz** [comment] 2020-05-03 16:00
@JPH71 No problem! I can continue to manually add the posters until then. Thanks for all your help!
