### ISSUE TITLE
Issues with RuntimeWarning and Agents not working

### ISSUE THREAD

**Issue by crospa91** [CodyBerenson/PGMA-Modernized#93] opened 2021-04-22 11:14 UTC
Today I've noticed a very weird issue with the agent.
I'm using Plex inside a docker container and since the first installation today, I've started receiving these errors in the log of the container:

`
/config/Library/Application Support/Plex Media Server/Plug-ins/WayBig.bundle/Contents/Libraries/Shared/unidecode/__init__.py:64: RuntimeWarning: Argument <type 'str'> is not an unicode object. Passing an encoded string will likely have unexpected results.`

and again

`
/config/Library/Application Support/Plex Media Server/Plug-ins/IAFD.bundle/Contents/Libraries/Shared/urllib3/connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.iafd.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings`

I saw your installation guide is written to be done on windows but, I tried anyway on docker.

can't really figure it our what's it's going on here.

In the agent log you can find these messages:

`2021-04-22 11:22:19,132 (7feade7fc700) :  INFO (sandbox:19) - WayBig  - GENF  :: Title Comparison              [Failed]	Site: "AJ Blackwood Fucks Asher (a.k.a. Ricky Donovan)"	File: Full/Short Title - "AJ Blackwood Fucks Asher" / "AJ Blackwood Fucks Asher"
2021-04-22 11:22:19,132 (7feade7fc700) :  ERROR (sandbox:19) - WayBig - SEARCH:: Error getting Site Title: Title Match Failure!
2021-04-22 11:22:19,133 (7feade7fc700) :  INFO (sandbox:19) - WayBig  -       ------------------------------------------------------------------------`

In more details:

`2021-04-22 11:33:08,824 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - GENF  :: Site Title                    AJ Blackwood Fucks Asher (a.k.a. Ricky Donovan)
2021-04-22 11:33:08,825 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - GENF  :: Title Comparison              [Failed] Site: "AJ Blackwood Fucks Asher (a.k.a. Ricky Donovan)" File: Full/Short Title - "AJ Blackwood Fucks Asher" / "AJ Blackwood Fucks Asher"
2021-04-22 11:33:08,825 (7f9447fff700) :  ERROR (sandbox:19) - WayBig - SEARCH:: Error getting Site Title: Title Match Failure!
`

It's clear that there is something going on with the agent, because the website respond correctly and the file name match exactly what the website want, so I don't really know where to bang my head anymore.

Full Log from the Agent:

`2021-04-22 11:33:08,791 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - SEARCH:: Preferences:
2021-04-22 11:33:08,792 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - SEARCH::  > Cast Legend Before Summary: False
2021-04-22 11:33:08,792 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - SEARCH::  > Collection Gathering
2021-04-22 11:33:08,793 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - SEARCH::      > Cast                  : False
2021-04-22 11:33:08,793 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - SEARCH::      > Director(s)           : False
2021-04-22 11:33:08,793 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - SEARCH::      > Studio                : True
2021-04-22 11:33:08,794 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - SEARCH::      > Film Title            : True
2021-04-22 11:33:08,794 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - SEARCH::      > Genres                : True
2021-04-22 11:33:08,795 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - SEARCH::  > Delay                     : 10
2021-04-22 11:33:08,795 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - SEARCH::  > Language Detection        : False
2021-04-22 11:33:08,795 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - SEARCH::  > Library:Site Language     : en:en
2021-04-22 11:33:08,796 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - SEARCH:: Media Title                  : Sean Cody Aj Blackwood Fucks Asher
2021-04-22 11:33:08,796 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - SEARCH:: File Name                    : (Sean Cody) - AJ Blackwood Fucks Asher
2021-04-22 11:33:08,797 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - SEARCH:: File Folder                  : /xxx-library/scenes
2021-04-22 11:33:08,797 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - ------------------------------------------------------------------------------
2021-04-22 11:33:08,804 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - GENF  :: Film Dictionary Variables:
2021-04-22 11:33:08,804 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - GENF  :: Collection                   : ['Sean Cody']
2021-04-22 11:33:08,805 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - GENF  :: CompareIAFDStudio            :
2021-04-22 11:33:08,805 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - GENF  :: CompareStudio                : seancody
2021-04-22 11:33:08,805 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - GENF  :: CompareTitle                 : ['aaabccdefhjkkloorssuw']
2021-04-22 11:33:08,806 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - GENF  :: Compilation                  : No
2021-04-22 11:33:08,806 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - GENF  :: FoundOnIAFD                  : No
2021-04-22 11:33:08,806 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - GENF  :: IAFDCompareTitle             : ['aaabccdefhjkkloorssuw']
2021-04-22 11:33:08,806 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - GENF  :: IAFDSearchTitle              : AJ+Blackwood+Fucks+Asher
2021-04-22 11:33:08,807 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - GENF  :: IAFDShortTitle               : AJ Blackwood Fucks Asher
2021-04-22 11:33:08,807 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - GENF  :: IAFDStudio                   :
2021-04-22 11:33:08,807 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - GENF  :: IAFDTitle                    : AJ Blackwood Fucks Asher
2021-04-22 11:33:08,807 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - GENF  :: SearchTitle                  : AJ Blackwood Fucks Asher
2021-04-22 11:33:08,808 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - GENF  :: Series                       : []
2021-04-22 11:33:08,808 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - GENF  :: ShortTitle                   : AJ Blackwood Fucks Asher
2021-04-22 11:33:08,808 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - GENF  :: Studio                       : Sean Cody
2021-04-22 11:33:08,808 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - GENF  :: Title                        : AJ Blackwood Fucks Asher
2021-04-22 11:33:08,808 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - ------------------------------------------------------------------------------
2021-04-22 11:33:08,809 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - AGNT  :: Original Search Query        : AJ Blackwood Fucks Asher
2021-04-22 11:33:08,809 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - AGNT  :: Search Query:: String has none of these (‘|’)
2021-04-22 11:33:08,810 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - AGNT  :: Search Query:: First word has none of these ('|"|`|“|”|‘|’)
2021-04-22 11:33:08,810 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - AGNT  :: Search Query:: First character has none of these ('|"|`|“|”|‘|’)
2021-04-22 11:33:08,810 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - AGNT  :: Search Query:: Split not attempted. String has none of these ('|"|`|“|”|‘|’)
2021-04-22 11:33:08,811 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - AGNT  :: Returned Search Query        : aj+blackwood+fucks+asher
2021-04-22 11:33:08,811 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - ------------------------------------------------------------------------------
2021-04-22 11:33:08,811 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - SEARCH:: Search Title: aj+blackwood+fucks+asher
2021-04-22 11:33:08,812 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - SEARCH:: Search Title: aj+blackwood+fucks+asher
2021-04-22 11:33:08,812 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - SEARCH:: Search Query: https://www.waybig.com/blog/index.php?s=aj+blackwood+fucks+asher
2021-04-22 11:33:08,813 (7f9447fff700) :  DEBUG (networking:138) - Fetching 'https://www.waybig.com/blog/index.php?s=aj+blackwood+fucks+asher' from the HTTP cache
2021-04-22 11:33:08,823 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - SEARCH:: No More Pages Found
2021-04-22 11:33:08,824 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - SEARCH:: Result Page No: 1, Titles Found 1
2021-04-22 11:33:08,824 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - ------------------------------------------------------------------------------
2021-04-22 11:33:08,824 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - SEARCH:: Site Entry:                   SeanCody: AJ Blackwood Fucks Asher (a.k.a. Ricky Donovan)
2021-04-22 11:33:08,824 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - ------------------------------------------------------------------------------
2021-04-22 11:33:08,824 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - GENF  :: Site Title                    AJ Blackwood Fucks Asher (a.k.a. Ricky Donovan)
2021-04-22 11:33:08,825 (7f9447fff700) :  INFO (sandbox:19) - WayBig  - GENF  :: Title Comparison              [Failed] Site: "AJ Blackwood Fucks Asher (a.k.a. Ricky Donovan)" File: Full/Short Title - "AJ Blackwood Fucks Asher" / "AJ Blackwood Fucks Asher"
2021-04-22 11:33:08,825 (7f9447fff700) :  ERROR (sandbox:19) - WayBig - SEARCH:: Error getting Site Title: Title Match Failure!
2021-04-22 11:33:08,825 (7f9447fff700) :  INFO (sandbox:19) - WayBig  -       ------------------------------------------------------------------------
2021-04-22 11:33:08,826 (7f9447fff700) :  DEBUG (runtime:88) - Sending packed state data (106 bytes)
2021-04-22 11:33:08,826 (7f9447fff700) :  DEBUG (runtime:924) - Response: [200] str, 320 bytes
2021-04-22 11:33:08,829 (7f9447fff700) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.WayBig/messaging/function/X0FnZW50S2l0OkVyYXNlTWV0YWRhdGE_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMgpzNQpNb3ZpZXMxMAptZWRpYV90eXBlczQ4CmNvbS5wbGV4YXBwLmFnZW50cy5HYXlBZHVsdFNjZW5>
2021-04-22 11:33:08,830 (7f9447fff700) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.WayBig/messaging/function/X0FnZW50S2l0OkVyYXNlTWV0YWRhdGE_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMgpzNQpNb3ZpZXMxMAptZWRpYV90eXBlczQ4CmNvbS5wbGV4YXBwLmFnZW50cy5HYXlBZHVsdFNjZW5>
2021-04-22 11:33:08,831 (7f9447fff700) :  DEBUG (runtime:88) - Sending packed state data (106 bytes)
2021-04-22 11:33:08,831 (7f9447fff700) :  DEBUG (runtime:924) - Response: [200] str, 16 bytes`

**Comment by CodyBerenson** [comment] 2021-04-22 11:39
Hi @mattia

Jason will respond and help troubleshoot the technical issues.  However, I
have a question.  You specifically say:   "I saw your installation guide is
written to be done on windows but, I tried anyway on docker."  We thought
we wrote the guide to be PMS platform agnostic (although we do speak to a
file naming limitation in windows not allowing the use of a colon
(:)....can you show me where the guide is written as you say?  A fresh set
of eyes may have discovered something that wasn't intended.

Cheers.

**Comment by crospa91** [comment] 2021-04-22 11:42
Hey Cody, I just based that because the guide clearly tell the user to click in the tray icon and select "Quit" from the Plex Media Server Icon, that of course not the case on Docker or linux, where no system tray icon is available.

**Comment by JPH71** [comment] 2021-04-22 13:42
This has to do with the issue that when you reconstitute a Json dump it
converts string characters to Unicode.
I have highlighted this before and it is going to be corrected soon - it
happens in the scenes agents that sometimes have to parse the titles to get
cast etc...
I am working on Waybig tonight and will implement the fix in it, followed
by the other scene agents and later the film agents.

Cheers

Jason

**Comment by CodyBerenson** [comment] 2021-04-22 13:56
@jph71 please consider working this "string characters to Unicode" separately from #89.  The fix for #89 can be pushed to the repository and not get held up while while you then work directly with @crospa91 

@crospa91 
I'll have no way of testing progress made against this issue so will you reach out directly to Jason at jp.hudson@gmail.com and the two of you can work offline?  Once all is good, I'll regression test the agents to make nothing broke in the process.

**Comment by crospa91** [comment] 2021-04-22 14:34
Sure thing! If the issues are separate then no problem for me to test the fix for the issue with the agent.

I'll drop you an email right now so you can tell me when you're ready to let me test the new edited version of the agent!

**Comment by crospa91** [comment] 2021-04-28 11:47
Hey @CodyBerenson, Jason told me that he sent you the updated version for the agent of Waybig, any chance you tested it already so I can test it as well with the files that weren't matching?

Thanks!

**Comment by CodyBerenson** [comment] 2021-04-28 12:57
Hi @crospa91 Super busy work schedule this morning, but will test it as soon as some time frees up.  

Cheers

**Comment by crospa91** [comment] 2021-04-28 12:58
No problem at all!

Thanks!

**Comment by CodyBerenson** [comment] 2021-04-28 13:10
@crospa91 @JPH71 
I should have asked.  Sorry!  Were you able to resolve the environment differences offline and they're incorporated in this Waybig release?

**Comment by crospa91** [comment] 2021-04-28 13:16
For what Jason told me yesterday the fix for the matching it’s in that release he sent you, so yes

**Comment by JPH71** [comment] 2021-04-28 13:18
Darned it @crospa91, when you mentioned unicode <str> I sorted out an issue
with an issue I had seen before in the scene scrappers...
I have never used docker... make sure that the version of python you have
installed on the system is 2.7 as that is what Plex uses... though it has
its on version of python installed with it...
Most of the imported libraries will not have error logging that will filter
upwards to the agent...

grr... we will have to start looking at it more closely together as I am
working from home next week...

Jason

**Comment by crospa91** [comment] 2021-04-28 13:21
for reference, I'm using the linuxserver.io Plex Image, and from their description python 2.7 is included inside the docker container.

If you have a way to share the modified version of the waybill agent it take me literally 3 second to test it out and give you a feedback if the workaround applied is working already!

**Comment by JPH71** [comment] 2021-04-28 13:22
@crospa91 and @codyberenson I am trying to get the cloudflare to run
correctly in python 2.7.1 as I get some errors saying that the syntax is
wrong as the libraries cody was given seem to be using Python 3....

GEVI at the moment is not working for me.... So as soon as I fix this, we
can sort out the docker issue. But test the new version that I sent Cody as
hopefully all the variables that are know in use in the FILMDICT variable
as string rather than a mixture of Unicode and string

Jason

**Comment by JPH71** [comment] 2021-04-28 13:24
hold on - let me send it to you
https://drive.google.com/file/d/1P81nPmqBZxWh0c7mBaC6Ty7WL9j61m9k/view?usp=sharing

here it is

**Comment by crospa91** [comment] 2021-04-28 13:24
Fantastic! Let me updating on the server and I'll let you know ASAP

**Comment by crospa91** [comment] 2021-04-28 13:44
Changed the agent, but it won't start:

Error starting framework core for /config/Library/Application Support/Plex Media Server/Plug-ins/WayBig.bundle.

I'm trying to remove remove it and reupload it

**Comment by crospa91** [comment] 2021-04-28 13:45
Error starting framework core for /config/Library/Application Support/Plex Media Server/Plug-ins/WayBig.bundle.

Critical: libusb_init failed

**Comment by CodyBerenson** [comment] 2021-04-28 14:53
@crospa91 Agreed.  @JPH71 The WayBig agent won't load for me either.  

[com.plexapp.system.log](https://github.com/CodyBerenson/PGMA-Modernized/files/6392769/com.plexapp.system.log)

**Comment by JPH71** [comment] 2021-04-28 23:50
Does this file exist? C:\Users\jphud\AppData\Local\Plex Media
Server\Plug-ins\WayBig.bundle\Contents\info.plist
the system can't seem to find it according to the error log.... but I
zipped the whole folder

**Comment by CodyBerenson** [comment] 2021-04-29 00:59
@JPH71 
LOL.  I took another look.  In the .zip, the bundle was nested within a folder of the same name.  Once I copied the true bundle, restarted PMS, it correctly fixes the issues from #94 as expected.  Sorry for the confusion.  I'll push to the master branch now.

**Comment by CodyBerenson** [comment] 2021-04-29 01:17
@JPH71 
LOL, you were right.  I took a look and realized that the bundle was nested within a folder of the same name.  Once I retried, the bundle loaded fine.  However, please see the update I made to #94 re: what this fix broke.  Sorry.

**Comment by crospa91** [comment] 2021-05-02 08:18
Oh I've put the folder directly in plex! let me retry as well!

**Comment by crospa91** [comment] 2021-05-02 08:21
And @CodyBerenson  agreed, plugin loads fine but I can relate with the same issue of https://github.com/CodyBerenson/PGMA-Modernized/issues/94 no actor get matched now with the new Waybig agent.

**Comment by CodyBerenson** [comment] 2021-05-02 13:44
@crospa91 

Cloudflare/non matching actors aside, if i follow correctly, this does fix the environment issues you were having before?

**Comment by crospa91** [comment] 2021-05-03 14:54
Yes @CodyBerenson the issue with the runtime is gone

**Comment by crospa91** [comment] 2021-05-06 11:08
Sorry to bother you guys, any update on this issue?

**Comment by crospa91** [comment] 2021-05-06 11:25
Today the new version of the agent that Cody made it's not working anymore for me... returned the same error, but the file is in the right folder. and the .plist is there and with the right permissions

**Comment by CodyBerenson** [comment] 2021-05-06 22:12
@crospa91 Hello.  I'm sorry, my friend.  I haven't heard from Jason and am unaware of his timeline. Thanks for your patience.

**Comment by JPH71** [comment] 2021-05-06 23:20
@crospa91 <https://github.com/crospa91> - I am just about to send GEVI,
Waybig and Fagalicious to Cody...
They should be in the repository as soon as Cody tests them...
I have been on call for the past 10 days and not had much time to work on
them.

**Comment by crospa91** [comment] 2021-05-07 06:52
No worries at all! No rush either, was just checking at what point we were because I didn't heard anything back!

As always massive thank you for all your help in this!

**Comment by CodyBerenson** [comment] 2021-05-07 12:08
Greetings @crospa91  

Jason @JPH71 fixed a number of outstanding issues with GEVI, Fagalicious and WayBig....and perhaps the challenges you've faced but I have no way of testing.  Please download the latest code, copy to your plugins directory, stop and then restart your PMS, and advise when you have a chance.

**Comment by crospa91** [comment] 2021-05-17 15:24
Hey guys, apologies for the super late reply.
today I've managed to install the plugins, but I got welcomed by lots of issues... 


Error starting framework core for /config/Library/Application Support/Plex Media Server/Plug-ins/WayBig.bundle.

/config/Library/Application Support/Plex Media Server/Plug-ins/QueerClick.bundle/Contents/Libraries/Shared/unidecode/__init__.py:64: RuntimeWarning: Argument <type 'str'> is not an unicode object. Passing an encoded string will likely have unexpected results.

  _warn_if_not_unicode(string)

/config/Library/Application Support/Plex Media Server/Plug-ins/BestExclusivePorn.bundle/Contents/Libraries/Shared/unidecode/__init__.py:64: RuntimeWarning: Argument <type 'str'> is not an unicode object. Passing an encoded string will likely have unexpected results.

  _warn_if_not_unicode(string)

/config/Library/Application Support/Plex Media Server/Plug-ins/IAFD.bundle/Contents/Libraries/Shared/unidecode/__init__.py:64: RuntimeWarning: Argument <type 'str'> is not an unicode object. Passing an encoded string will likely have unexpected results.

  _warn_if_not_unicode(string)

/config/Library/Application Support/Plex Media Server/Plug-ins/IAFD.bundle/Contents/Libraries/Shared/urllib3/connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.iafd.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

  InsecureRequestWarning,

**Comment by JPH71** [comment] 2021-05-17 17:57
@crospa91

What version of waybig are you using??
Best thing to do - clear your logs and do a "Refresh Metadata" on the one
scene that is causing you this issue.
Then send the log file over.
Do this as standard in the future, as I can then easily identify what is
causing the issue.

I had made some changes to Waybig, along with fagalicious which Cody has
already tested.
I will be sending the latest version to Cody, later on tonight.

In the meantime at least give me the name of the Scene you are trying to
match

**Comment by JPH71** [comment] 2022-02-27 23:25
@crospa91 - Is this sorted out??

**Comment by crospa91** [comment] 2022-02-27 23:42
Hey there. 
The issues seems getting better but i still find the agent very oddly not recognising movies and scene. I know the naming need to be precise but even if i try manually to search for scene, the results are quite sparse with “non standard” scenes. 

But i guess there is no solution for that…

**Comment by JPH71** [comment] 2022-03-12 14:05
Give me a list of movies and their URLs and I will check into it.

Jason

**Comment by JPH71** [comment] 2022-12-20 23:27
can this be marked as fixed

**Comment by CodyBerenson** [comment] 2022-12-21 02:14
@JPH71 Closed!

**Closed** 2022-12-29 03:19 UTC
Labels: help wanted
